services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ytasty
      POSTGRES_PASSWORD: ytasty
      POSTGRES_DB: ytasty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://ytasty:ytasty@db:5432/ytasty
      SECRET_KEY: 0da7e4229afdb663de5bf46c9c54e3a7a83f801a6b41b43405c55b8748d9c1c8
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  